# .pre-commit-config.yaml
repos:
  - repo: https://github.com/psf/black
    rev: 25.12.0  # <-- set this to the exact version you use in your project
    hooks:
      - id: black
        language_version: python3.14  # your Python version

  - repo: https://github.com/pycqa/isort
    rev: 7.0.0  # <-- set to the version your project uses
    hooks:
      - id: isort
        language_version: python3.14

  - repo: local
    hooks:
      - id: run-tests
        name: Run unit tests
        entry: bash -c 'export PYTHONPATH=$PWD && poetry run pytest'
        language: system
        pass_filenames: false